version: "3.9"

services:
  web:
    environment:
      DB_USER: tides
      DB_PASS: tides
      DB_HOST: postgres
      DB_PORT: 5432
      DATABASE_URL: postgres://tides:tides@postgres:5432/tides_db?sslmode=allow
      PGHOST: postgres
      PGUSER: tides
      PGPASSWORD: tides
      PGPORT: 5432
      PGSSLMODE: allow
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./ci_static:/app/staticfiles
      - ./ci_media:/app/data
      - ./ci_snid_api_runs:/snid_api_runs
      - ./ci_ngsf_api_runs:/ngsf_api_runs

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tides
      POSTGRES_PASSWORD: tides
      POSTGRES_DB: tides_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tides -d tides_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  snid_api:
    volumes:
      - ./ci_snid_api_runs:/snid_api_runs
      - ./ci_media:/media

  ngsf_api:
    volumes:
      - ./ci_ngsf_api_runs:/ngsf_api_runs
