version: "3.9"

services:
  web:
    build: .
    command: ['gunicorn', 'tidestom.wsgi:application', '--bind', '0.0.0.0:8000', '--workers', '4', '--worker-class', 'gevent','--log-level', 'debug', '--capture-output', '--enable-stdio-inheritance']
    cpus: 4
    ports:
      - "8000:8000"
    depends_on:
      snid_api:
        condition: service_healthy
      ngsf_api:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/data
      - snid_api_runs:/snid_api_runs
      - ngsf_api_runs:/ngsf_api_runs
    environment:
      LOCAL_MODE: 'True'
      TIDES_TEST_DIR: 'test_data/'
      DB_PASS: ${DB_PASS}
      DATABASE_URL: ${DATABASE_URL}
      PGHOST: ${DB_HOST}
      PGUSER: ${DB_USER}
      PGPASSWORD: ${DB_PASS}
      PGPORT: ${DB_PORT}
      PGDATABSE: defaultdb
      PGSSLMODE: require

      # Django settings
      DJANGO_SECRET_KEY: "u-a)en=plsciz3d4(2*yc()4(1=#@o)bkdusqho3kx%)i&amp;0cy"
      DJANGO_SETTINGS_MODULE: tidestom.settings
      SNID_API_URL: http://snid_api:8000
      NGSF_API_URL: http://ngsf_api:8000
    networks:
      - backend

  nginx:
    image: nginx:1.25
    cpus: 1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static
      - media_volume:/media
      - snid_api_runs:/snid_api_runs
      - ngsf_api_runs:/ngsf_api_runs
    ports:
      - "8080:80"
    depends_on:
      - web
      - snid_api
      - ngsf_api

#  snid_api:
#    build: ./snid_docker/
#    cpus: 4
#    expose:
#      - "8000"
#    environment:
#      DJANGO_URL: http://web:8000
#    volumes:
#      - snid_api_runs:/snid_api_runs
#      - media_volume:/media
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
#      interval: 5s
#      retries: 10
#      start_period: 10s
#      timeout: 2s

#  ngsf_api:
#    build: ./ngsf_docker/
#    cpus: 4
#    expose:
#      - "8000"
#    environment:
#      DJANGO_URL: http://web:8000
#    volumes:
#      - ngsf_api_runs:/ngsf_api_runs
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
#      interval: 5s
#      retries: 10
#      start_period: 10s
#      timeout: 2s

volumes:
  static_volume:
  #media_volume:
  #  external: true
  #snid_api_runs:
  #  external: true
  #ngsf_api_runs:
  #  external: true
  #
networks:
  backend:
    external: true
