version: "3.9"

services:
  web:
    environment:
      DB_USER: tides
      DB_PASS: tides
      DB_HOST: postgres
      DB_PORT: 5432
      DATABASE_URL: postgres://tides:tides@postgres:5432/tides_db?sslmode=allow
      PGHOST: postgres
      PGUSER: tides
      PGPASSWORD: tides
      PGPORT: 5432
      PGSSLMODE: allow
    depends_on:
      postgres:
        condition: service_healthy
      
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: tides
      POSTGRES_PASSWORD: tides
      POSTGRES_DB: tides_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tides -d tides_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  media_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ci_media
  snid_api_runs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ci_snid_api_runs
  ngsf_api_runs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ci_ngsf_api_runs
  static_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ci_static
