services:
  web:
    build: .
    command: gunicorn tidestom.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      TIDES_TEST_DIR: ${TIDES_TEST_DIR}
      DB_PASS: ${DB_PASS}
      # Remote PostgreSQL database connection
      DATABASE_URL: postgres://cf5g09:titanic2018@cannon.phys.soton.ac.uk/tidestom

      # Django settings
      DJANGO_SECRET_KEY: "u-a)en=plsciz3d4(2*yc()4(1=#@o)bkdusqho3kx%)i&amp;0cy"
      DJANGO_SETTINGS_MODULE: tidestom.settings

      # Optional: useful for debugging
      #PYTHONUNBUFFERED: 1
    #volumes:
    # - .:/app

