CLASSIFICATIONS = {
    "SNIa": ["Normal", "91bg-like", "Super-Chandrasekhar" "91T-like","99aa-like","02cx-like","CSM","pec"],
    "SNIb/c":[],
    "SNIb": ["Normal", "Ca-strong","n","pec"],
    "SNIc": ["Normal", "BL","n","pec"],
    "SNId": ["Normal", "n","pec"],
    "SNIe": ["Normal", "n","pec"],
    "SNII": ["Normal", "n",'b',"pec"],
    "SLSN": ["I", "II","IIn","pec"],
    "TDE": ["H","He","H+HE","H+He+Bowen","Featureless","pec"],
    "KN": [ "Red", "Blue", "pec"],
    "AGN": ["Broad Line", "Narrow Line", "pec"],
    "GRB": ["Afterglow",],
    "CV": [],
    "LBV": [],
    "LRN": [],
    "ILRT": [],
    "Star": ["O", "B", "A", "F", "G", "K", "M", "pec"],
    "Other": ["Unknown"],
}