# Generated by Django 4.2.20 on 2025-08-21 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tom_targets", "0026_alter_basetarget_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("obs_id", models.IntegerField(blank=True, null=True)),
                ("person_id", models.IntegerField(blank=True, null=True)),
                ("sn_type", models.CharField(max_length=50)),
                ("sn_z", models.FloatField(blank=True, null=True)),
                ("sn_subtype", models.CharField(blank=True, max_length=50, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField()),
            ],
            options={
                "db_table": "human_classifications",
                "ordering": ["-created"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineClassificationDash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sn_type", models.CharField(blank=True, max_length=50, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "pipeline_classification_dash",
                "ordering": ["-probability"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineClassificationEd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sn_type", models.CharField(blank=True, max_length=50, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "pipeline_classification_ed",
                "ordering": ["-probability"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineClassificationGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sn_type", models.CharField(blank=True, max_length=50, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pipeline_classification_global",
                "ordering": ["-probability"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineClassificationSnid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sn_type", models.CharField(blank=True, max_length=50, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "pipeline_classification_snid",
                "ordering": ["-probability"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineClassificationSuperfit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sn_type", models.CharField(blank=True, max_length=50, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "pipeline_classification_superfit",
                "ordering": ["-probability"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TidesClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "tides_class",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TidesClassSubClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_class", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "tides_class_subclass",
                "ordering": ["main_class_id", "sub_class"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TidesSpec",
            fields=[
                ("qmost_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("sn_type", models.CharField(blank=True, max_length=50, null=True)),
                ("obs_date", models.DateTimeField(blank=True, null=True)),
                ("obs_mjd", models.FloatField(blank=True, null=True)),
                ("snr", models.FloatField(blank=True, null=True)),
                ("seeing", models.FloatField(blank=True, null=True)),
                ("sky_brightness", models.FloatField(blank=True, null=True)),
                ("filepath", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField(blank=True, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "tides_spec",
                "ordering": ["-obs_date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TidesTarget",
            fields=[
                (
                    "target_ptr",
                    models.OneToOneField(
                        db_column="tides_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tom_targets.basetarget",
                    ),
                ),
                (
                    "lsst_sn_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("lsst_host_id", models.BigIntegerField(blank=True, null=True)),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("z_best", models.FloatField(blank=True, null=True)),
                ("z_sn", models.FloatField(blank=True, null=True)),
                ("z_gal", models.FloatField(blank=True, null=True)),
                ("z_source", models.CharField(blank=True, max_length=50, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "target",
                "db_table": "tides_cand",
                "managed": False,
            },
            bases=("tom_targets.basetarget",),
        ),
    ]
