# Generated by Django 4.2.14 on 2025-06-13 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tom_targets", "0021_rename_target_basetarget_alter_basetarget_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tides_id", models.BigIntegerField()),
                ("obs_id", models.IntegerField(blank=True, null=True)),
                ("person_id", models.IntegerField()),
                ("sn_type", models.CharField(max_length=50)),
                ("sn_z", models.FloatField(blank=True, null=True)),
                ("sn_subtype", models.CharField(blank=True, max_length=100, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "human_classifications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PipelineClassificationGlobal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sn_type", models.CharField(blank=True, max_length=50, null=True)),
                ("probability", models.FloatField(blank=True, null=True)),
                ("version", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "pipeline_classification_global",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TidesSpec",
            fields=[
                ("tides_id", models.BigIntegerField()),
                ("qmost_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("sn_type", models.CharField(blank=True, max_length=50, null=True)),
                ("obs_date", models.DateTimeField(blank=True, null=True)),
                ("obs_mjd", models.FloatField(blank=True, null=True)),
                ("snr", models.FloatField(blank=True, null=True)),
                ("seeing", models.FloatField(blank=True, null=True)),
                ("sky_brightness", models.FloatField(blank=True, null=True)),
                ("filepath", models.TextField(blank=True, null=True)),
                ("version", models.IntegerField(blank=True, null=True)),
                ("additional_info", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "tides_spec",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TidesTarget",
            fields=[
                ("tides_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("lsst_sn_id", models.BigIntegerField(unique=True)),
                ("lsst_host_id", models.BigIntegerField(blank=True, null=True)),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("z_best", models.FloatField(blank=True, null=True)),
                ("z_sn", models.FloatField(blank=True, null=True)),
                ("z_gal", models.FloatField(blank=True, null=True)),
                ("z_source", models.CharField(blank=True, max_length=50, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "tides_target",
                "db_table": "tides_cand",
                "permissions": (
                    ("view_target", "View Target"),
                    ("add_target", "Add Target"),
                    ("change_target", "Change Target"),
                    ("delete_target", "Delete Target"),
                ),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MirroredTidesTarget",
            fields=[
                (
                    "basetarget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="tom_targets.basetarget",
                    ),
                ),
                ("tides_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("lsst_sn_id", models.BigIntegerField(unique=True)),
                ("lsst_host_id", models.BigIntegerField(blank=True, null=True)),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("z_best", models.FloatField(blank=True, null=True)),
                ("z_sn", models.FloatField(blank=True, null=True)),
                ("z_gal", models.FloatField(blank=True, null=True)),
                ("z_source", models.CharField(blank=True, max_length=50, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "target",
                "managed": True,
            },
            bases=("tom_targets.basetarget",),
        ),
    ]
