# Generated by Django 4.2.14 on 2025-06-13 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mirroredtidestarget",
            options={"managed": True, "verbose_name": "tides_target"},
        ),
        migrations.AlterModelOptions(
            name="tidestarget",
            options={
                "managed": False,
                "permissions": (
                    ("view_target", "View Target"),
                    ("add_target", "Add Target"),
                    ("change_target", "Change Target"),
                    ("delete_target", "Delete Target"),
                ),
                "verbose_name": "backend_tides_target",
            },
        ),
    ]
