# Generated by Django 4.2.14 on 2024-12-19 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TidesClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="tidestarget",
            name="example_bool",
        ),
        migrations.RemoveField(
            model_name="tidestarget",
            name="example_number",
        ),
        migrations.AddField(
            model_name="tidestarget",
            name="tidesclass",
            field=models.CharField(
                choices=[
                    ("SN", "SN"),
                    ("SNI", "SNI"),
                    ("SNIa", "SNIa"),
                    ("SNIbc", "SNIbc"),
                    ("SNIb", "SNIb"),
                    ("SNIc", "SNIc"),
                    ("SNId", "SNId"),
                    ("SNIe", "SNIe"),
                    ("SNII", "SNII"),
                    ("SLSN-I", "SLSN-I"),
                    ("SLSN-II", "SLSN-II"),
                    ("TDE", "TDE"),
                    ("KN", "KN"),
                    ("AGN", "AGN"),
                    ("LRN", "LRN"),
                    ("CV", "CV"),
                    ("LBV", "LBV"),
                    ("Other", "Other"),
                ],
                default="SN",
                max_length=50,
                verbose_name="TiDES Classification",
            ),
        ),
        migrations.AddField(
            model_name="tidestarget",
            name="tidesclass_other",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="TiDES Classification (Other)",
            ),
        ),
        migrations.CreateModel(
            name="TidesClassSubClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_class", models.CharField(max_length=100)),
                (
                    "main_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_classes",
                        to="custom_code.tidesclass",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tidestarget",
            name="tidesclass_subclass",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="custom_code.tidesclasssubclass",
                verbose_name="TiDES Sub-classification",
            ),
        ),
    ]
