# Generated by Django 4.2.14 on 2025-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_code", "0002_alter_mirroredtidestarget_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TidesCand",
            fields=[
                ("tides_id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("lsst_sn_id", models.BigIntegerField(unique=True)),
                ("lsst_host_id", models.BigIntegerField(blank=True, null=True)),
                ("last_date", models.DateTimeField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("z_best", models.FloatField(blank=True, null=True)),
                ("z_sn", models.FloatField(blank=True, null=True)),
                ("z_gal", models.FloatField(blank=True, null=True)),
                ("z_source", models.CharField(blank=True, max_length=50, null=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "backend_tides_target",
                "db_table": "tides_cand",
                "permissions": (
                    ("view_target", "View Target"),
                    ("add_target", "Add Target"),
                    ("change_target", "Change Target"),
                    ("delete_target", "Delete Target"),
                ),
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="TidesTarget",
        ),
        migrations.AlterModelOptions(
            name="mirroredtidestarget",
            options={"managed": True, "verbose_name": "django_target"},
        ),
    ]
