name: allow-dev-only
on:
  pull_request:
    branches:
      - prod

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR comes from dev-deploy
        run: |
          if [ "${{ github.head_ref }}" != "dev-deploy" ]; then
            echo "Only dev-deploy may be merged into prod"
            exit 1
          fi
